/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * buscar_cliente.java
 *
 * Created on 13/08/2011, 09:32:02
 */

package pdvjonatas;

import utilitarios.bd;
import utilitarios.mySql;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.AbstractAction;
import javax.swing.DefaultListModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AttributeSet;
import javax.swing.text.PlainDocument;
/**
 *
 * @author AGENCIA GLOBO
 */
public class buscar_cliente extends javax.swing.JDialog {

    public String nome, cpf, codigo;
    /** Creates new form buscar_cliente */
    public buscar_cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        busca.requestFocus();

        busca.setDocument( new PlainDocument(){
            @Override
		protected void insertUpdate( DefaultDocumentEvent chng, AttributeSet attr ){

                        super.insertUpdate( chng, attr );

                        DefaultTableModel model = ((DefaultTableModel)clientes.getModel());
                        model.setNumRows(0);

                        bd b = new bd();
                        b.connect();
                        mySql f = new mySql(b.conn);
                        String sql = "Select * FROM CLIENTE WHERE nome LIKE '%"+busca.getText().toLowerCase()+"%' OR nome LIKE '%"+busca.getText().toUpperCase()+"%' OR cnpj_cnpf = '"+busca.getText() +"' OR codigo ='"+busca.getText()+"' ORDER BY nome ASC";
                        f.open(sql);
                        while (f.next()){
                             model.addRow(new Object [] {f.fieldbyname("codigo"), f.fieldbyname("nome"),f.fieldbyname("cnpj_cnpf")} );
                        }


                       
		}
        });
    }


    public String getNome(){
        return nome;
    }

    public String getCpf(){
        return cpf;
    }

    public String getCodigo(){
        return codigo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        busca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientes = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nome ou CPF:");

        clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "CPF"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(clientes);

        jButton1.setText("Selecionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(busca))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(busca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked
        if (evt.getClickCount() == 2){
            DefaultTableModel model = ((DefaultTableModel)clientes.getModel());
            try{
            nome = model.getValueAt(clientes.getSelectedRow(), 1).toString();
            cpf  = model.getValueAt(clientes.getSelectedRow(), 2).toString();
            codigo = model.getValueAt(clientes.getSelectedRow(), 0).toString();
            }catch (Exception e){
                nome = model.getValueAt(clientes.getSelectedRow(), 1).toString();
                cpf  = "";
                codigo = model.getValueAt(clientes.getSelectedRow(), 0).toString();
            }
            dispose();
        }
    }//GEN-LAST:event_clientesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = ((DefaultTableModel)clientes.getModel());
        try{
            nome = model.getValueAt(clientes.getSelectedRow(), 1).toString();
            cpf  = model.getValueAt(clientes.getSelectedRow(), 2).toString();
            codigo = model.getValueAt(clientes.getSelectedRow(), 0).toString();
            dispose();
        }catch (Exception e){
            nome = model.getValueAt(clientes.getSelectedRow(), 1).toString();
            cpf  = "";
            codigo = model.getValueAt(clientes.getSelectedRow(), 0).toString();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                buscar_cliente dialog = new buscar_cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busca;
    private javax.swing.JTable clientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
