/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pdvjonatas;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.text.BadLocationException;
import utilitarios.bd;
import utilitarios.mySql;
import utilitarios.nivelUsuario;

/**
 *
 * @author Jonatas
 */
public class frameLogin extends javax.swing.JDialog {

    public static boolean itemDescAcres = false;
    public static boolean itemCancelar = false;
    public static boolean cupomDescAcres = false;
    public static boolean cupomCancelar = false;
    /**
     * Creates new form frameLogin
     */
    public frameLogin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        sair = new javax.swing.JButton();
        entrar = new javax.swing.JButton();
        senha = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setText("Infome usuário e senha para entrar no sistema:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(210, 90, 270, 14);

        jLabel3.setText("Usuário: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 120, 50, 20);

        jLabel4.setText("Senha:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 145, 50, 20);

        usuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                usuarioKeyPressed(evt);
            }
        });
        getContentPane().add(usuario);
        usuario.setBounds(360, 120, 120, 20);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        getContentPane().add(sair);
        sair.setBounds(411, 180, 70, 23);

        entrar.setText("Entrar");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        getContentPane().add(entrar);
        entrar.setBounds(330, 180, 70, 23);

        senha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaKeyPressed(evt);
            }
        });
        getContentPane().add(senha);
        senha.setBounds(360, 145, 120, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/gdoor-login.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 497, 272);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logIn(){
        bd b = new bd();
        b.connect();
        mySql f = new mySql(b.conn);
       /* String senhaAux = new String(senha.getPassword());
        String queryAux = "";
        if (senhaAux.length() ==   1){
            if (Character.isLetter(senhaAux.charAt(0))){
                queryAux = "senha ='"+senhaAux+"'";
            }else{
                queryAux = "senha ="+senhaAux+"";
            }
        }else{
            queryAux = "senha ='"+senhaAux+"'";
        }
        
        System.out.println("SELECT USUARIO FROM USUARIOS WHERE usuario = '"+usuario.getText()+ "' and "+ queryAux);
        f.open("SELECT usuario FROM USUARIOS WHERE usuario = '"+usuario.getText()+ "' and "+ queryAux);*/
        //System.out.println("SELECT USUARIO FROM USUARIOS WHERE usuario = '"+usuario.getText()+"' AND senha ='"+new String(senha.getPassword())+"'");
        f.open("SELECT * FROM USUARIOS WHERE usuario = '"+usuario.getText()+"' AND senha ='"+new String(senha.getPassword())+"'");
        if (f.next()){
            //System.out.println(f.fieldbyname("usuario"));
            dispose();
            Main.vendedor = usuario.getText();
            
            f.open("SELECT * FROM USER_ACESSO WHERE USUARIO = '"+usuario.getText()+"' AND MODULO = 'Frente de Caixa' "
                    + "AND ACESSO ='Operador'");
            /*String user = "";
            while(f.next()){
                user = f.fieldbyname("modulo");
            }
            
            if (!user.equals("")){*/
            if (f.next() || usuario.getText().equals("ADMINISTRADOR")){
                
                nivelUsuario n = new nivelUsuario();
                n.nivelUser(usuario.getText());
                
                framePrincipal p = null;
                try {
                    p = new framePrincipal();
                } catch (BadLocationException ex) {
                    Logger.getLogger(frameLogin.class.getName()).log(Level.SEVERE, null, ex);
                }
                p.setVisible(true);
                p.setSize(800, 600);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Usuário não habilitado para usar o Módulo de Frente de Caixa");
                System.exit(0);
            }
  
        }else{
            JOptionPane.showMessageDialog(rootPane, "Usuário ou senha inválido");
            usuario.requestFocus();
            
        }
    }
    
    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
        logIn();
    }//GEN-LAST:event_entrarActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
       System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void usuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_usuarioKeyPressed
        //System.out.println(evt.getKeyCode());
        if (evt.getKeyCode() == 10){
            senha.requestFocus();
        }
    }//GEN-LAST:event_usuarioKeyPressed

    private void senhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaKeyPressed
        if (evt.getKeyCode() == 10){
            if (usuario.getText().equals("")){
                usuario.requestFocus();
            }else
                if (new String(senha.getPassword()).equals("")){
                    java.awt.Toolkit.getDefaultToolkit().beep();  
                }else
                logIn();
        }
    }//GEN-LAST:event_senhaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frameLogin dialog = new frameLogin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton entrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton sair;
    private javax.swing.JPasswordField senha;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
